### ISSUE TITLE
read(::SampleSource, ::SampleBuf) can read wrong number of frames from source

### ISSUE THREAD

**Issue by martinholters** [JuliaAudio/SampledSignals.jl#18]
Example:
```Julia
julia> typeof(inputstream)
LibSndFile.SndFileSource{FixedPointNumbers.Fixed{Int16,15}}

julia> inputstream.pos
1

julia> read!(inputstream, SampleBuf(Array{Float64}(10), samplerate(inputstream)))
10

julia> inputstream.pos
4097
```

The problem is that the forwarding to `write(::SampleSink, ::SampleSource)` [here](https://github.com/JuliaAudio/SampledSignals.jl/blob/7866a6981d4bb95c24cb1d30ace169e657dbf890/src/SampleStream.jl#L179) looses the buffer length. I guess changing it to `write(SampleBufSink(buf), source, nframes(buf))` should suffice to fix this issue, at least it works for me.

**Comment by ssfrr** [comment]
Thanks, this is definitely a problem, and I think your fix would fix the `SampleBufSink` case just fine.

There's a more general problem which is that if you write a `Source` to a `Sink` and the `Sink` ends early, you may have read too much from the `Source` and the data gets lost. I guess there aren't a lot of examples of finite-length `Sinks` aside from this one, so maybe fixing this case is good enough for now. I'll write a test and fix it in the next couple days when I have some time to think about it a little more deeply.
