### ISSUE TITLE
cannot display SampleBuf in jupyterlab

### ISSUE THREAD

**Issue by clouds56** [JuliaAudio/SampledSignals.jl#24]
when display some SampleBuf, it outputs
```
SampleBuf display requires javascript
To enable for the whole notebook select "Trust Notebook" from the "File" menu. You can also trust this cell by re-running it. You may also need to re-run `using SampledSignals` if the module is not yet loaded in the Julia kernel, or `SampledSignals.embed_javascript()` if the Julia module is loaded but the javascript isn't initialized.
```
and in the devtools of chrome, it warns
```
JupyterLab does not execute inline JavaScript in HTML output
```

see this issue for more details https://github.com/jupyterlab/jupyterlab/issues/2666

**Comment by ssfrr** [comment]
hmm. that's unfortunate. I'm checking with the jupyterlab maintainers to figure out what the new "right way" to provide this feature would be.

Thanks for the report!

**Comment by ssfrr** [comment]
For now I've just simplified the display so it should work in any browser context. It's not as slick of a player but it should work.
