### ISSUE TITLE
Shouldn't time be the *last* index?

### ISSUE THREAD

**Issue by danmackinlay** [JuliaAudio/SampledSignals.jl#48]
If I have got the array stacking of julia correct then... Since Julia is column-arranged, it seem logical that time index should always be last - otherwise if I am playing a 7.1 WAV file, rather than pulling all 8 channels from 8 discontiguous memory, I am pulling it from one contiguous block. Or have I transposed this in my feeble brain?

**Comment by ssfrr** [comment]
This isn't super clear-cut. From a streaming perspective it makes sense for samples to be interleaved in memory, but once you're working with a buffer of audio, my assumption is that many operations will be per-channel, so it's useful to have that channel's data contiguous in memory.
