### ISSUE TITLE
Project.toml:[compat] section causing compatibility issues with `Compat.jl`

### ISSUE THREAD

**Issue by ma-laforge** [JuliaAudio/SampledSignals.jl#69]
Many packages rely on `Compat.jl`. If at all possible, it would be good for this package to be compatible with version 3+:
```
[compat]
Compat = "2, 3"
```

Right now, it is set to `Compat = "2"`, yet Compat.jl has moved on to v3.27.

Until this is changed, adding `SampledSignals.jl` to my environment will force packages like `HDF5.jl` to get downgraded to significantly outdated versions.

It would be nice if you could cut a new release that resolves this issue.

Thanks.

**Comment by rob-luke** [comment]
Thanks for the feedback @ma-laforge. Is your issue now resolved if you use the master branch? I will try and cut a new release in the next week or two.

**Comment by rob-luke** [comment]
Thanks for checking @ma-laforge.

I'll be working on updating infrastructure etc in the coming weeks. So please feel free to post issues for any other troubles you run in to.
